export enum Tag {
    BUILDING = 'building',
    SPACE = 'space',
    SCIENCE = 'science',
    POWER = 'power',
    EARTH = 'earth',
    JOVIAN = 'jovian',
    VENUS = 'venus',
    PLANT = 'plant',
    MICROBE = 'microbe',
    ANIMAL = 'animal',
    CITY = 'city',
    MOON = 'moon',
    MARS = 'mars',
    WILD = 'wild',
    EVENT = 'event',
    CLONE = 'clone',
    THEOLOGY = 'theology',
    PRAYER = 'prayer',
    OUTREACH = 'outreach',
    DISCIPLESHIP = 'discipleship',
    PROPHECY = 'prophecy',
    GOSPEL_SPREAD = 'gospel_spread',
    PROPHECIES_FULFILLED = 'prophecies_fulfilled',
    UNREACHED = 'unreached',
}

export const ALL_TAGS = [
  Tag.BUILDING,
  Tag.SPACE,
  Tag.SCIENCE,
  Tag.POWER,
  Tag.EARTH,
  Tag.JOVIAN,
  Tag.VENUS,
  Tag.MOON,
  Tag.MARS,
  Tag.PLANT,
  Tag.MICROBE,
  Tag.ANIMAL,
  Tag.CITY,
  Tag.WILD,
  Tag.EVENT,
  Tag.CLONE,
  Tag.THEOLOGY,
  Tag.PRAYER,
  Tag.OUTREACH,
  Tag.DISCIPLESHIP,
  Tag.PROPHECY,
  Tag.GOSPEL_SPREAD,
  Tag.PROPHECIES_FULFILLED,
  Tag.UNREACHED
] as const;
